import sys
from .pattern import S, F, I, Control
# Create functions for making control patterns (patterns of dictionaries)

generic_params = [
    (S, "toArg", "for internal sound routing"),
    # (F, "from", "for internal sound routing"),  <- TODO - 'from' is a reserved word in python..
    (F, "to", "for internal sound routing"),
    (F, "accelerate", "a pattern of numbers that speed up (or slow down) samples while they play."),
    (F, "amp", "like @gain@, but linear."),
    (F, "attack", "a pattern of numbers to specify the attack time (in seconds) of an envelope applied to each sample."),
    (F, "bandf", "a pattern of numbers from 0 to 1. Sets the center frequency of the band-pass filter."),
    (F, "bandq", "a pattern of anumbers from 0 to 1. Sets the q-factor of the band-pass filter."),
    (F, "begin", "a pattern of numbers from 0 to 1. Skips the beginning of each sample, e.g. `0.25` to cut off the first quarter from each sample."),
    (F, "legato", "controls the amount of overlap between two adjacent sounds"),
    (F, "clhatdecay", ""),
    (F, "crush", "bit crushing, a pattern of numbers from 1 (for drastic reduction in bit-depth) to 16 (for barely no reduction)."),
    (F, "coarse", "fake-resampling, a pattern of numbers for lowering the sample rate, i.e. 1 for original 2 for half, 3 for a third and so on."),
    (I, "channel", "choose the channel the pattern is sent to in superdirt"),
    (I, "cut", "In the style of classic drum-machines, `cut` will stop a playing sample as soon as another samples with in same cutgroup is to be played. An example would be an open hi-hat followed by a closed one, essentially muting the open."),
    (F, "cutoff", "a pattern of numbers from 0 to 1. Applies the cutoff frequency of the low-pass filter."),
    (F, "cutoffegint", ""),
    (F, "decay", ""),
    (F, "delay", "a pattern of numbers from 0 to 1. Sets the level of the delay signal."),
    (F, "delayfeedback", "a pattern of numbers from 0 to 1. Sets the amount of delay feedback."),
    (F, "delaytime", "a pattern of numbers from 0 to 1. Sets the length of the delay."),
    (F, "detune", ""),
    (F, "djf", "DJ filter, below 0.5 is low pass filter, above is high pass filter."),
    (F, "dry", "when set to `1` will disable all reverb for this pattern. See `room` and `size` for more information about reverb."),
    (F, "end", "the same as `begin`, but cuts the end off samples, shortening them; e.g. `0.75` to cut off the last quarter of each sample."),
    (F, "fadeTime", "Used when using begin/end or chop/striate and friends, to change the fade out time of the 'grain' envelope."),
    (F, "fadeInTime", "As with fadeTime, but controls the fade in time of the grain envelope. Not used if the grain begins at position 0 in the sample."),
    (F, "freq", ""),
    (F, "gain", "a pattern of numbers that specify volume. Values less than 1 make the sound quieter. Values greater than 1 make the sound louder. For the linear equivalent, see @amp@."),
    (F, "gate", ""),
    (F, "hatgrain", ""),
    (F, "hcutoff", "a pattern of numbers from 0 to 1. Applies the cutoff frequency of the high-pass filter. Also has alias @hpf@"),
    (F, "hold", "a pattern of numbers to specify the hold time (in seconds) of an envelope applied to each sample. Only takes effect if `attack` and `release` are also specified."),
    (F, "hresonance", "a pattern of numbers from 0 to 1. Applies the resonance of the high-pass filter. Has alias @hpq@"),
    (F, "lagogo", ""),
    (F, "lclap", ""),
    (F, "lclaves", ""),
    (F, "lclhat", ""),
    (F, "lcrash", ""),
    (F, "leslie", ""),
    (F, "lrate", ""),
    (F, "lsize", ""),
    (F, "lfo", ""),
    (F, "lfocutoffint", ""),
    (F, "lfodelay", ""),
    (F, "lfoint", ""),
    (F, "lfopitchint", ""),
    (F, "lfoshape", ""),
    (F, "lfosync", ""),
    (F, "lhitom", ""),
    (F, "lkick", ""),
    (F, "llotom", ""),
    (F, "lock", "A pattern of numbers. Specifies whether delaytime is calculated relative to cps. When set to 1, delaytime is a direct multiple of a cycle."),
    (F, "loop", "loops the sample (from `begin` to `end`) the specified number of times."),
    (F, "lophat", ""),
    (F, "lsnare", ""),
    (F, "n", "The note or sample number to choose for a synth or sampleset"),
    (F, "note", "The note or pitch to play a sound or synth with"),
    (F, "degree", ""),
    (F, "mtranspose", ""),
    (F, "ctranspose", ""),
    (F, "harmonic", ""),
    (F, "stepsPerOctave", ""),
    (F, "octaveR", ""),
    (F, "nudge", "Nudges events into the future by the specified number of seconds. Negative numbers work up to a point as well (due to internal latency)"),
    (I, "octave", ""),
    (F, "offset", ""),
    (F, "ophatdecay", ""),
    (I, "orbit", "a pattern of numbers. An `orbit` is a global parameter context for patterns. Patterns with the same orbit will share hardware output bus offset and global effects, e.g. reverb and delay. The maximum number of orbits is specified in the superdirt startup, numbers higher than maximum will wrap around."),
    (F, "overgain", ""),
    (F, "overshape", ""),
    (F, "pan", "a pattern of numbers between 0 and 1, from left to right (assuming stereo), once round a circle (assuming multichannel)"),
    (F, "panspan", "a pattern of numbers between -inf and inf, which controls how much multichannel output is fanned out (negative is backwards ordering)"),
    (F, "pansplay", "a pattern of numbers between 0.0 and 1.0, which controls the multichannel spread range (multichannel only)"),
    (F, "panwidth", "a pattern of numbers between 0.0 and inf, which controls how much each channel is distributed over neighbours (multichannel only)"),
    (F, "panorient", "a pattern of numbers between -1.0 and 1.0, which controls the relative position of the centre pan in a pair of adjacent speakers (multichannel only)"),
    (F, "pitch1", ""),
    (F, "pitch2", ""),
    (F, "pitch3", ""),
    (F, "portamento", ""),
    (F, "rate", "used in SuperDirt softsynths as a control rate or 'speed'"),
    (F, "release", "a pattern of numbers to specify the release time (in seconds) of an envelope applied to each sample."),
    (F, "resonance", "a pattern of numbers from 0 to 1. Specifies the resonance of the low-pass filter."),
    (F, "room", "a pattern of numbers from 0 to 1. Sets the level of reverb."),
    (F, "sagogo", ""),
    (F, "sclap", ""),
    (F, "sclaves", ""),
    (F, "scrash", ""),
    (F, "semitone", ""),
    (F, "shape", "wave shaping distortion, a pattern of numbers from 0 for no distortion up to 1 for loads of distortion."),
    (F, "size", "a pattern of numbers from 0 to 1. Sets the perceptual size (reverb time) of the `room` to be used in reverb."),
    (F, "slide", ""),
    (F, "speed", "a pattern of numbers which changes the speed of sample playback, i.e. a cheap way of changing pitch. Negative values will play the sample backwards!"),
    (F, "squiz", ""),
    (F, "stutterdepth", ""),
    (F, "stuttertime", ""),
    (F, "sustain", ""),
    (F, "tomdecay", ""),
    (S, "unit", "used in conjunction with `speed`, accepts values of \"r\" (rate, default behavior), \"c\" (cycles), or \"s\" (seconds). Using `unit \"c\"` means `speed` will be interpreted in units of cycles, e.g. `speed \"1\"` means samples will be stretched to fill a cycle. Using `unit \"s\"` means the playback speed will be adjusted so that the duration is the number of seconds specified by `speed`."),
    (F, "velocity", ""),
    (F, "vcfegint", ""),
    (F, "vcoegint", ""),
    (F, "voice", ""),
    (S, "vowel", "formant filter to make things sound like vowels, a pattern of either `a`, `e`, `i`, `o` or `u`. Use a rest (`~`) for no effect."),
    (F, "waveloss", ""),
    (F, "dur", ""),
    (F, "modwheel", ""),
    (F, "expression", ""),
    (F, "sustainpedal", ""),
    (F, "tremolodepth", "Tremolo Audio DSP effect | params are 'tremolorate' and 'tremolodepth'"),
    (F, "tremolorate", "Tremolo Audio DSP effect | params are 'tremolorate' and 'tremolodepth'"),
    (F, "phaserdepth", "Phaser Audio DSP effect | params are 'phaserrate' and 'phaserdepth'"),
    (F, "phaserrate", "Phaser Audio DSP effect | params are 'phaserrate' and 'phaserdepth'"),
    (F, "fshift", "frequency shifter"),
    (F, "fshiftnote", "frequency shifter"),
    (F, "fshiftphase", "frequency shifter"),
    (F, "triode", "tube distortion"),
    (F, "krush", "shape/bass enhancer"),
    (F, "kcutoff", ""),
    (F, "octer", "octaver effect"),
    (F, "octersub", "octaver effect"),
    (F, "octersubsub", "octaver effect"),
    (F, "ring", "ring modulation"),
    (F, "ringf", "ring modulation"),
    (F, "ringdf", "ring modulation"),
    (F, "distort", "noisy fuzzy distortion"),
    (F, "freeze", "Spectral freeze"),
    (F, "xsdelay", ""),
    (F, "tsdelay", ""),
    (F, "real", "Spectral conform"),
    (F, "imag", ""),
    (F, "enhance", "Spectral enhance"),
    (F, "partials", ""),
    (F, "comb", "Spectral comb"),
    (F, "smear", "Spectral smear"),
    (F, "scram", "Spectral scramble"),
    (F, "binshift", "Spectral binshift"),
    (F, "hbrick", "High pass sort of spectral filter"),
    (F, "lbrick", "Low pass sort of spectral filter"),
    (F, "midichan", ""),
    (F, "control", ""),
    (F, "ccn", ""),
    (F, "ccv", ""),
    (F, "polyTouch", ""),
    (F, "midibend", ""),
    (F, "miditouch", ""),
    (F, "ctlNum", ""),
    (F, "frameRate", ""),
    (F, "frames", ""),
    (F, "hours", ""),
    (S, "midicmd", ""),
    (F, "minutes", ""),
    (F, "progNum", ""),
    (F, "seconds", ""),
    (F, "songPtr", ""),
    (F, "uid", ""),
    (F, "val", ""),
    (F, "cps", "")
]

controls = []

# This had to go in its own function, for weird scoping reasons..
def make_control(cls, name):
    setattr(cls, name, lambda pat: Control(pat.fmap(lambda v: {name: v}).query))

module_obj = sys.modules[__name__]

for cls, name, desc in generic_params:
    make_control(cls, name)
    setattr(module_obj,name,getattr(cls,name))
